export default {
  common: {
    appName: 'سعودي درايف',
    loading: 'جارِ التحميل...',
    error: 'حدث خطأ',
    retry: 'إعادة المحاولة',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    submit: 'إرسال',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    search: 'بحث',
    filter: 'تصفية',
    next: 'التالي',
    back: 'السابق',
    done: 'تم',
    seeAll: 'عرض الكل',
    sar: 'ر.س',
    day: 'يوم',
    days: 'أيام',
    hour: 'ساعة',
    hours: 'ساعات',
  },
  onboarding: {
    title1: 'استأجر سيارة بسهولة',
    subtitle1: 'ابحث واحجز سيارتك بنقرات قليلة',
    title2: 'اعرض سيارتك للإيجار',
    subtitle2: 'اكسب المال عن طريق تأجير سيارتك عندما لا تستخدمها',
    title3: 'آمن وموثوق',
    subtitle3: 'عملية التحقق لدينا تضمن السلامة لجميع الأطراف',
    getStarted: 'ابدأ الآن',
    skip: 'تخطي',
    chooseLanguage: 'اختر اللغة',
    english: 'English',
    arabic: 'العربية',
  },
  auth: {
    welcome: 'مرحباً بك في سعودي درايف',
    login: 'تسجيل الدخول',
    loginSubtitle: 'أدخل رقم هاتفك للمتابعة',
    register: 'تسجيل',
    phoneNumber: 'رقم الهاتف',
    phoneNumberPlaceholder: '05XXXXXXXX',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    enterOTP: 'أدخل رمز التحقق',
    otpSent: 'لقد أرسلنا رمز التحقق إلى',
    resendOTP: 'إعادة إرسال الرمز',
    seconds: 'ثانية',
    verifyPhone: 'تحقق من الهاتف',
    confirmOTP: 'تأكيد الرمز',
    createAccount: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    nationalId: 'الهوية الوطنية / الإقامة',
    driverLicense: 'رخصة القيادة',
    scanLicense: 'مسح الرخصة',
    takePicture: 'التقاط صورة',
    uploadFromGallery: 'تحميل من المعرض',
    licenseUploaded: 'تم تحميل الرخصة',
    termsConditions: 'بالمتابعة، أنت توافق على الشروط والأحكام',
  },
  home: {
    greeting: 'مرحباً',
    findCar: 'ابحث عن سيارتك المثالية',
    nearbyTitle: 'سيارات قريبة',
    featuredTitle: 'سيارات مميزة',
    popularTitle: 'سيارات شائعة',
    viewMap: 'عرض الخريطة',
    viewList: 'عرض القائمة',
    sortBy: 'ترتيب حسب',
    price: 'السعر',
    distance: 'المسافة',
    rating: 'التقييم',
    availability: 'التوفر',
    topRated: 'الأعلى تقييماً',
    instantBooking: 'حجز فوري',
    priceRange: 'نطاق السعر',
    carTypes: 'أنواع السيارات',
    sedan: 'سيدان',
    suv: 'دفع رباعي',
    luxury: 'فاخرة',
    sports: 'رياضية',
    economy: 'اقتصادية',
    applyFilters: 'تطبيق الفلاتر',
    resetFilters: 'إعادة ضبط الفلاتر',
    noResults: 'لم يتم العثور على سيارات',
    tryAdjustingFilters: 'حاول تعديل الفلاتر أو الموقع',
  },
  carDetails: {
    instantBooking: 'حجز فوري',
    requestBooking: 'طلب حجز',
    specifications: 'المواصفات',
    features: 'الميزات',
    rules: 'القواعد',
    reviews: 'التقييمات',
    availabilityCalendar: 'تقويم التوفر',
    aboutOwner: 'عن المالك',
    contactOwner: 'التواصل مع المالك',
    bookThisCar: 'احجز هذه السيارة',
    perDay: 'لليوم الواحد',
    year: 'السنة',
    doors: 'الأبواب',
    seats: 'المقاعد',
    transmission: 'ناقل الحركة',
    fuelType: 'نوع الوقود',
    mileage: 'المسافة المسموحة',
    auto: 'أوتوماتيك',
    manual: 'يدوي',
    gasoline: 'بنزين',
    diesel: 'ديزل',
    electric: 'كهربائية',
    hybrid: 'هجينة',
    unlimited: 'غير محدود',
    kmPerDay: 'كم/يوم',
    airConditioned: 'تكييف',
    bluetooth: 'بلوتوث',
    audioInput: 'مدخل صوت',
    gps: 'نظام تحديد المواقع',
    usbCharger: 'شاحن USB',
    noSmoking: 'ممنوع التدخين',
    noPets: 'ممنوع الحيوانات الأليفة',
    fuelPolicy: 'سياسة الوقود',
    lateReturn: 'التأخير في الإرجاع',
    additionalDrivers: 'سائقين إضافيين',
    roadTrips: 'رحلات طويلة',
    returnFull: 'الإرجاع بخزان ممتلئ',
    feePerHour: 'رسوم لكل ساعة',
    notAllowed: 'غير مسموح',
    allowed: 'مسموح برسوم',
    baseRating: 'بناءً على {count} تقييمات',
    reviewsCount: '{count} تقييم',
    writeReview: 'كتابة تقييم',
    selectDates: 'اختر التواريخ',
    pickupLocation: 'موقع الاستلام',
    dropoffLocation: 'موقع التسليم',
    joinedDate: 'انضم في {date}',
    responseRate: 'معدل الاستجابة {rate}%',
    responseTime: 'وقت الاستجابة {time}',
    verifiedUser: 'مستخدم موثق',
  },
  booking: {
    summary: 'ملخص الحجز',
    pickup: 'الاستلام',
    dropoff: 'التسليم',
    duration: 'المدة',
    insuranceOption: 'خيار التأمين',
    basicInsurance: 'تأمين أساسي',
    advancedInsurance: 'تأمين متقدم',
    premiumInsurance: 'تأمين متميز',
    subtotal: 'المجموع الفرعي',
    serviceFee: 'رسوم الخدمة',
    insuranceFee: 'رسوم التأمين',
    total: 'المجموع',
    paymentMethods: 'طرق الدفع',
    addPaymentMethod: 'إضافة طريقة دفع',
    bookNow: 'احجز الآن',
    confirmBooking: 'تأكيد الحجز',
    bookingConfirmed: 'تم تأكيد الحجز',
    bookingRequested: 'تم طلب الحجز',
    pendingOwnerApproval: 'في انتظار موافقة المالك',
    contactOwner: 'التواصل مع المالك',
    viewBooking: 'عرض الحجز',
    selectDate: 'اختر التاريخ',
    selectTime: 'اختر الوقت',
    enterLocation: 'أدخل الموقع',
    useCurrentLocation: 'استخدم الموقع الحالي',
    enterAddress: 'أدخل العنوان',
    city: 'المدينة',
    district: 'الحي',
    street: 'الشارع',
    buildingNumber: 'رقم المبنى',
    additionalDirections: 'توجيهات إضافية',
  },
  profile: {
    title: 'الملف الشخصي',
    personalInfo: 'المعلومات الشخصية',
    myListings: 'إعلاناتي',
    myBookings: 'حجوزاتي',
    inbox: 'صندوق الوارد',
    paymentMethods: 'طرق الدفع',
    settings: 'الإعدادات',
    help: 'المساعدة والدعم',
    logout: 'تسجيل الخروج',
    editProfile: 'تعديل الملف الشخصي',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    driverLicense: 'رخصة القيادة',
    changePassword: 'تغيير كلمة المرور',
    deleteAccount: 'حذف الحساب',
    language: 'اللغة',
    notifications: 'الإشعارات',
    darkMode: 'الوضع الداكن',
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    contactSupport: 'التواصل مع الدعم',
    faqs: 'الأسئلة الشائعة',
    aboutUs: 'عن التطبيق',
    version: 'الإصدار',
  },
  listings: {
    myListings: 'إعلاناتي',
    addNewListing: 'إضافة إعلان جديد',
    active: 'نشط',
    inactive: 'غير نشط',
    pending: 'قيد الانتظار',
    rejected: 'مرفوض',
    editListing: 'تعديل الإعلان',
    deleteListing: 'حذف الإعلان',
    deleteConfirm: 'هل أنت متأكد من حذف هذا الإعلان؟',
    addCarDetails: 'أضف تفاصيل السيارة',
    make: 'الشركة المصنعة',
    model: 'الموديل',
    year: 'السنة',
    plate: 'رقم اللوحة',
    color: 'اللون',
    transmission: 'ناقل الحركة',
    fuelType: 'نوع الوقود',
    doors: 'الأبواب',
    seats: 'المقاعد',
    mileage: 'حد المسافة',
    addCarPhotos: 'أضف صور السيارة',
    mainPhoto: 'الصورة الرئيسية',
    additionalPhotos: 'صور إضافية',
    addPhoto: 'إضافة صورة',
    exteriorPhoto: 'خارجية',
    interiorPhoto: 'داخلية',
    frontPhoto: 'أمامية',
    backPhoto: 'خلفية',
    documentPhoto: 'وثيقة التسجيل',
    setPricing: 'تعيين الأسعار',
    baseDailyRate: 'السعر اليومي الأساسي',
    weeklyDiscount: 'خصم أسبوعي',
    monthlyDiscount: 'خصم شهري',
    setAvailability: 'تعيين التوفر',
    alwaysAvailable: 'متاح دائماً',
    customAvailability: 'توفر مخصص',
    setLocation: 'تعيين موقع الاستلام/التسليم',
    specificLocation: 'موقع محدد',
    flexibleLocation: 'مرن ضمن المنطقة',
    addFeatures: 'إضافة الميزات والمرافق',
    addRules: 'إضافة القواعد والسياسات',
    publishListing: 'نشر الإعلان',
    saveDraft: 'حفظ كمسودة',
    preview: 'معاينة',
    instantBooking: 'تمكين الحجز الفوري',
    instantBookingInfo: 'السماح للمستخدمين بالحجز فوراً بدون موافقة',
  },
  bookings: {
    myBookings: 'حجوزاتي',
    upcoming: 'القادمة',
    ongoing: 'الجارية',
    past: 'السابقة',
    canceled: 'الملغاة',
    bookingDetails: 'تفاصيل الحجز',
    bookingID: 'رقم الحجز',
    status: 'الحالة',
    bookedOn: 'تم الحجز في',
    dates: 'التواريخ',
    time: 'الوقت',
    total: 'المجموع',
    viewReceipt: 'عرض الإيصال',
    cancelBooking: 'إلغاء الحجز',
    cancelPolicy: 'سياسة الإلغاء',
    modifyBooking: 'تعديل الحجز',
    contactOwner: 'التواصل مع المالك',
    contactRenter: 'التواصل مع المستأجر',
    leaveReview: 'ترك تقييم',
    confirmPickup: 'تأكيد الاستلام',
    confirmReturn: 'تأكيد الإرجاع',
    reportIssue: 'الإبلاغ عن مشكلة',
    extendRental: 'تمديد الإيجار',
    approved: 'تمت الموافقة',
    declined: 'مرفوض',
    pending: 'قيد الانتظار',
    canceled: 'ملغى',
    completed: 'مكتمل',
    ongoing: 'جارٍ',
  },
  messages: {
    inbox: 'صندوق الوارد',
    chats: 'المحادثات',
    notifications: 'الإشعارات',
    noMessages: 'لا توجد رسائل بعد',
    startConversation: 'ابدأ محادثة مع مالك أو مستأجر',
    typeMessage: 'اكتب رسالة...',
    send: 'إرسال',
    bookingRequest: 'طلب حجز',
    bookingApproved: 'تمت الموافقة على الحجز',
    bookingDeclined: 'تم رفض الحجز',
    newMessage: 'رسالة جديدة',
    seeDetails: 'عرض التفاصيل',
    reply: 'رد',
  },
  reviews: {
    writeReview: 'كتابة تقييم',
    rateCar: 'تقييم السيارة',
    rateOwner: 'تقييم المالك',
    rateRenter: 'تقييم المستأجر',
    overallExperience: 'التجربة العامة',
    cleanliness: 'النظافة',
    maintenance: 'الصيانة',
    accuracy: 'دقة الإعلان',
    communication: 'التواصل',
    convenience: 'الراحة',
    leaveComment: 'اترك تعليقاً',
    reviewPlaceholder: 'شارك تجربتك...',
    submitReview: 'إرسال التقييم',
    thankYou: 'شكراً على تقييمك',
    reviewSubmitted: 'تم إرسال تقييمك بنجاح',
    minimumChars: 'مطلوب 10 أحرف على الأقل',
  },
  payment: {
    payment: 'الدفع',
    paymentMethods: 'طرق الدفع',
    addPaymentMethod: 'إضافة طريقة دفع',
    creditCard: 'بطاقة ائتمان',
    debitCard: 'بطاقة الخصم',
    mada: 'مدى',
    applePay: 'آبل باي',
    sadad: 'سداد',
    stcPay: 'إس تي سي باي',
    cardNumber: 'رقم البطاقة',
    nameOnCard: 'الاسم على البطاقة',
    expiryDate: 'تاريخ الانتهاء',
    cvv: 'رمز التحقق',
    saveCard: 'حفظ البطاقة للمدفوعات المستقبلية',
    makeDefault: 'جعلها الافتراضية',
    billingAddress: 'عنوان الفواتير',
    sameAsProfile: 'نفس عنوان الملف الشخصي',
    paymentSuccessful: 'تم الدفع بنجاح',
    paymentFailed: 'فشل الدفع',
    tryAgain: 'حاول مرة أخرى',
    chooseAnotherMethod: 'اختر طريقة أخرى',
    totalAmount: 'المبلغ الإجمالي',
    processingFee: 'رسوم المعالجة',
    grandTotal: 'المجموع الكلي',
    payNow: 'ادفع الآن',
  },
};