export default {
  common: {
    appName: 'SaudiDrive',
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    cancel: 'Cancel',
    confirm: 'Confirm',
    submit: 'Submit',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    filter: 'Filter',
    next: 'Next',
    back: 'Back',
    done: 'Done',
    seeAll: 'See All',
    sar: 'SAR',
    day: 'Day',
    days: 'Days',
    hour: 'Hour',
    hours: 'Hours',
  },
  onboarding: {
    title1: 'Rent a Car Easily',
    subtitle1: 'Find and book your car rental in just a few taps',
    title2: 'List Your Car for Rent',
    subtitle2: 'Earn extra money by renting out your car when not in use',
    title3: 'Safe and Secure',
    subtitle3: 'Our verification process ensures safety for all parties',
    getStarted: 'Get Started',
    skip: 'Skip',
    chooseLanguage: 'Choose Language',
    english: 'English',
    arabic: 'العربية',
  },
  auth: {
    welcome: 'Welcome to SaudiDrive',
    login: 'Login',
    loginSubtitle: 'Enter your mobile number to continue',
    register: 'Register',
    phoneNumber: 'Phone Number',
    phoneNumberPlaceholder: '05XXXXXXXX',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    enterOTP: 'Enter OTP',
    otpSent: 'We have sent a verification code to',
    resendOTP: 'Resend OTP',
    seconds: 'seconds',
    verifyPhone: 'Verify Phone',
    confirmOTP: 'Confirm OTP',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: 'Don\'t have an account?',
    fullName: 'Full Name',
    email: 'Email',
    nationalId: 'National ID / Iqama',
    driverLicense: 'Driver\'s License',
    scanLicense: 'Scan License',
    takePicture: 'Take Picture',
    uploadFromGallery: 'Upload from Gallery',
    licenseUploaded: 'License Uploaded',
    termsConditions: 'By continuing, you agree to our Terms & Conditions',
  },
  home: {
    greeting: 'Hello',
    findCar: 'Find your perfect car',
    nearbyTitle: 'Cars Nearby',
    featuredTitle: 'Featured Cars',
    popularTitle: 'Popular Cars',
    viewMap: 'View Map',
    viewList: 'View List',
    sortBy: 'Sort By',
    price: 'Price',
    distance: 'Distance',
    rating: 'Rating',
    availability: 'Availability',
    topRated: 'Top Rated',
    instantBooking: 'Instant Booking',
    priceRange: 'Price Range',
    carTypes: 'Car Types',
    sedan: 'Sedan',
    suv: 'SUV',
    luxury: 'Luxury',
    sports: 'Sports',
    economy: 'Economy',
    applyFilters: 'Apply Filters',
    resetFilters: 'Reset Filters',
    noResults: 'No cars found',
    tryAdjustingFilters: 'Try adjusting your filters or location',
  },
  carDetails: {
    instantBooking: 'Instant Booking',
    requestBooking: 'Request Booking',
    specifications: 'Specifications',
    features: 'Features',
    rules: 'Rules',
    reviews: 'Reviews',
    availabilityCalendar: 'Availability Calendar',
    aboutOwner: 'About Owner',
    contactOwner: 'Contact Owner',
    bookThisCar: 'Book This Car',
    perDay: 'per day',
    year: 'Year',
    doors: 'Doors',
    seats: 'Seats',
    transmission: 'Transmission',
    fuelType: 'Fuel Type',
    mileage: 'Mileage',
    auto: 'Automatic',
    manual: 'Manual',
    gasoline: 'Gasoline',
    diesel: 'Diesel',
    electric: 'Electric',
    hybrid: 'Hybrid',
    unlimited: 'Unlimited',
    kmPerDay: 'km/day',
    airConditioned: 'Air Conditioned',
    bluetooth: 'Bluetooth',
    audioInput: 'Audio Input',
    gps: 'GPS',
    usbCharger: 'USB Charger',
    noSmoking: 'No Smoking',
    noPets: 'No Pets',
    fuelPolicy: 'Fuel Policy',
    lateReturn: 'Late Return',
    additionalDrivers: 'Additional Drivers',
    roadTrips: 'Road Trips',
    returnFull: 'Return with Full Tank',
    feePerHour: 'Fee per Hour',
    notAllowed: 'Not Allowed',
    allowed: 'Allowed with Fee',
    baseRating: 'Based on {count} reviews',
    reviewsCount: '{count} Reviews',
    writeReview: 'Write a Review',
    selectDates: 'Select Dates',
    pickupLocation: 'Pickup Location',
    dropoffLocation: 'Dropoff Location',
    joinedDate: 'Joined {date}',
    responseRate: '{rate}% Response Rate',
    responseTime: '{time} Response Time',
    verifiedUser: 'Verified User',
  },
  booking: {
    summary: 'Booking Summary',
    pickup: 'Pickup',
    dropoff: 'Dropoff',
    duration: 'Duration',
    insuranceOption: 'Insurance Option',
    basicInsurance: 'Basic Insurance',
    advancedInsurance: 'Advanced Insurance',
    premiumInsurance: 'Premium Insurance',
    subtotal: 'Subtotal',
    serviceFee: 'Service Fee',
    insuranceFee: 'Insurance Fee',
    total: 'Total',
    paymentMethods: 'Payment Methods',
    addPaymentMethod: 'Add Payment Method',
    bookNow: 'Book Now',
    confirmBooking: 'Confirm Booking',
    bookingConfirmed: 'Booking Confirmed',
    bookingRequested: 'Booking Requested',
    pendingOwnerApproval: 'Pending Owner Approval',
    contactOwner: 'Contact Owner',
    viewBooking: 'View Booking',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    enterLocation: 'Enter Location',
    useCurrentLocation: 'Use Current Location',
    enterAddress: 'Enter Address',
    city: 'City',
    district: 'District',
    street: 'Street',
    buildingNumber: 'Building Number',
    additionalDirections: 'Additional Directions',
  },
  profile: {
    title: 'My Profile',
    personalInfo: 'Personal Information',
    myListings: 'My Listings',
    myBookings: 'My Bookings',
    inbox: 'Inbox',
    paymentMethods: 'Payment Methods',
    settings: 'Settings',
    help: 'Help & Support',
    logout: 'Logout',
    editProfile: 'Edit Profile',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    driverLicense: 'Driver\'s License',
    changePassword: 'Change Password',
    deleteAccount: 'Delete Account',
    language: 'Language',
    notifications: 'Notifications',
    darkMode: 'Dark Mode',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    contactSupport: 'Contact Support',
    faqs: 'FAQs',
    aboutUs: 'About Us',
    version: 'Version',
  },
  listings: {
    myListings: 'My Listings',
    addNewListing: 'Add New Listing',
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    rejected: 'Rejected',
    editListing: 'Edit Listing',
    deleteListing: 'Delete Listing',
    deleteConfirm: 'Are you sure you want to delete this listing?',
    addCarDetails: 'Add Car Details',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    plate: 'License Plate',
    color: 'Color',
    transmission: 'Transmission',
    fuelType: 'Fuel Type',
    doors: 'Doors',
    seats: 'Seats',
    mileage: 'Mileage Limit',
    addCarPhotos: 'Add Car Photos',
    mainPhoto: 'Main Photo',
    additionalPhotos: 'Additional Photos',
    addPhoto: 'Add Photo',
    exteriorPhoto: 'Exterior',
    interiorPhoto: 'Interior',
    frontPhoto: 'Front',
    backPhoto: 'Back',
    documentPhoto: 'Registration Document',
    setPricing: 'Set Pricing',
    baseDailyRate: 'Base Daily Rate',
    weeklyDiscount: 'Weekly Discount',
    monthlyDiscount: 'Monthly Discount',
    setAvailability: 'Set Availability',
    alwaysAvailable: 'Always Available',
    customAvailability: 'Custom Availability',
    setLocation: 'Set Pickup/Dropoff Location',
    specificLocation: 'Specific Location',
    flexibleLocation: 'Flexible Within Area',
    addFeatures: 'Add Features and Amenities',
    addRules: 'Add Rules and Policies',
    publishListing: 'Publish Listing',
    saveDraft: 'Save as Draft',
    preview: 'Preview',
    instantBooking: 'Enable Instant Booking',
    instantBookingInfo: 'Allow users to book instantly without approval',
  },
  bookings: {
    myBookings: 'My Bookings',
    upcoming: 'Upcoming',
    ongoing: 'Ongoing',
    past: 'Past',
    canceled: 'Canceled',
    bookingDetails: 'Booking Details',
    bookingID: 'Booking ID',
    status: 'Status',
    bookedOn: 'Booked On',
    dates: 'Dates',
    time: 'Time',
    total: 'Total',
    viewReceipt: 'View Receipt',
    cancelBooking: 'Cancel Booking',
    cancelPolicy: 'Cancellation Policy',
    modifyBooking: 'Modify Booking',
    contactOwner: 'Contact Owner',
    contactRenter: 'Contact Renter',
    leaveReview: 'Leave Review',
    confirmPickup: 'Confirm Pickup',
    confirmReturn: 'Confirm Return',
    reportIssue: 'Report Issue',
    extendRental: 'Extend Rental',
    approved: 'Approved',
    declined: 'Declined',
    pending: 'Pending',
    canceled: 'Canceled',
    completed: 'Completed',
    ongoing: 'Ongoing',
  },
  messages: {
    inbox: 'Inbox',
    chats: 'Chats',
    notifications: 'Notifications',
    noMessages: 'No Messages Yet',
    startConversation: 'Start a conversation with an owner or renter',
    typeMessage: 'Type a message...',
    send: 'Send',
    bookingRequest: 'Booking Request',
    bookingApproved: 'Booking Approved',
    bookingDeclined: 'Booking Declined',
    newMessage: 'New Message',
    seeDetails: 'See Details',
    reply: 'Reply',
  },
  reviews: {
    writeReview: 'Write a Review',
    rateCar: 'Rate the Car',
    rateOwner: 'Rate the Owner',
    rateRenter: 'Rate the Renter',
    overallExperience: 'Overall Experience',
    cleanliness: 'Cleanliness',
    maintenance: 'Maintenance',
    accuracy: 'Listing Accuracy',
    communication: 'Communication',
    convenience: 'Convenience',
    leaveComment: 'Leave a Comment',
    reviewPlaceholder: 'Share your experience...',
    submitReview: 'Submit Review',
    thankYou: 'Thank You for Your Review',
    reviewSubmitted: 'Your review has been submitted successfully',
    minimumChars: 'Minimum 10 characters required',
  },
  payment: {
    payment: 'Payment',
    paymentMethods: 'Payment Methods',
    addPaymentMethod: 'Add Payment Method',
    creditCard: 'Credit Card',
    debitCard: 'Debit Card',
    mada: 'Mada',
    applePay: 'Apple Pay',
    sadad: 'SADAD',
    stcPay: 'STC Pay',
    cardNumber: 'Card Number',
    nameOnCard: 'Name on Card',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    saveCard: 'Save Card for Future Payments',
    makeDefault: 'Make Default',
    billingAddress: 'Billing Address',
    sameAsProfile: 'Same as Profile Address',
    paymentSuccessful: 'Payment Successful',
    paymentFailed: 'Payment Failed',
    tryAgain: 'Try Again',
    chooseAnotherMethod: 'Choose Another Method',
    totalAmount: 'Total Amount',
    processingFee: 'Processing Fee',
    grandTotal: 'Grand Total',
    payNow: 'Pay Now',
  },
};